// <copyright file="EmployeeTest.CalculateSalary.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace PexDemo
{
    public partial class EmployeeTest
    {
[TestMethod]
[PexGeneratedBy(typeof(EmployeeTest))]
public void CalculateSalary866()
{
    decimal d;
    Employee s0 = new Employee();
    d = this.CalculateSalary(s0, 0);
    Assert.AreEqual<decimal>(100000e-2M, d);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(EmployeeTest))]
public void CalculateSalary912()
{
    decimal d;
    Employee s0 = new Employee();
    d = this.CalculateSalary(s0, 4);
    Assert.AreEqual<decimal>(25000e-2M, d);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(EmployeeTest))]
[ExpectedException(typeof(ArgumentException))]
public void CalculateSalaryThrowsArgumentException499()
{
    decimal d;
    Employee s0 = new Employee();
    d = this.CalculateSalary(s0, 21);
}
[TestMethod]
[PexGeneratedBy(typeof(EmployeeTest))]
public void CalculateSalary94()
{
    decimal d;
    Employee s0 = new Employee();
    d = this.CalculateSalary(s0, 20);
    Assert.AreEqual<decimal>(200000e-2M, d);
    Assert.IsNotNull((object)s0);
}
[TestMethod]
[PexGeneratedBy(typeof(EmployeeTest))]
public void CalculateSalary240()
{
    decimal d;
    Employee s0 = new Employee();
    d = this.CalculateSalary(s0, 5);
    Assert.AreEqual<decimal>(150000e-2M, d);
    Assert.IsNotNull((object)s0);
}
    }
}
